# Generated by Django 2.1.4 on 2018-12-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='aadhar_id',
            field=models.IntegerField(),
        ),
    ]
