# Generated by Django 2.1.4 on 2018-12-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0002_auto_20181215_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='historydata',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
