# Generated by Django 2.1.4 on 2018-12-15 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_auto_20181215_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydata',
            name='premium',
        ),
    ]
